---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: hyprdynamicmonitors-rc

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
      main: main.go
      ldflags: |
          -s -w
          -X github.com/fiffeek/hyprdynamicmonitors/cmd.Version={{ .Version }}
          -X github.com/fiffeek/hyprdynamicmonitors/cmd.Commit={{ .ShortCommit }}
          -X github.com/fiffeek/hyprdynamicmonitors/cmd.BuildDate={{ .Date }}
      binary: hyprdynamicmonitors-rc

archives:
    - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      files:
          - LICENSE

changelog:
    sort: asc
    filters:
        exclude:
            - '(?i)^docs?:'
            - '(?i)^docs\([^:]+\):'
            - '(?i)^docs\[[^:]+\]:'
            - '^tests?:'
            - '(?i)^dev:'
            - '(?i)^chore:'
            - '(?i)^style:'
            - '(?i)^refactor:'
            - '^build\(deps\): bump .* in /docs \(#\d+\)'
            - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
            - Merge pull request
            - Merge branch
release:
    skip_upload: false
    draft: true
    replace_existing_draft: true
    make_latest: false
    prerelease: 'true'
    github:
        owner: fiffeek
        name: hyprdynamicmonitors

aurs:
    - description: Dynamic monitor configuration for Hyprland (release candidate).
      skip_upload: false
      homepage: https://github.com/fiffeek/hyprdynamicmonitors
      provides:
          - hyprdynamicmonitors-rc-bin
      maintainers:
          - Filip Mikina <filipmikina at gmail dot com>
      license: MIT
      private_key: '{{ .Env.AUR_KEY }}'
      git_url: ssh://aur@aur.archlinux.org/hyprdynamicmonitors-rc-bin.git
      optdepends:
          - hyprland
          - upower
      commit_author:
          name: Filip Mikina
          email: filipmikina@gmail.con
      package: |-
          # bin
          install -Dm755 "./hyprdynamicmonitors-rc" "${pkgdir}/usr/bin/hyprdynamicmonitors-rc"

          # license
          install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/hyprdynamicmonitors-rc/LICENSE"

          # completions
          mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
          mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
          mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
          ./hyprdynamicmonitors completion bash | install -Dm644 /dev/stdin "${pkgdir}/usr/share/bash-completion/completions/hyprdynamicmonitors-rc"
          ./hyprdynamicmonitors completion zsh | install -Dm644 /dev/stdin "${pkgdir}/usr/share/zsh/site-functions/_hyprdynamicmonitors-rc"
          ./hyprdynamicmonitors completion fish | install -Dm644 /dev/stdin "${pkgdir}/usr/share/fish/vendor_completions.d/hyprdynamicmonitors-rc.fish"
