---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
      main: ./cmd/main.go
      ldflags: -s -w -X main.Version={{ .Version }} -X main.Commit={{ .ShortCommit }} -X main.BuildDate={{ .Date }}
      binary: hyprdynamicmonitors

archives:
    - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      files:
          - LICENSE

changelog:
    sort: asc
    filters:
        exclude:
            - '(?i)^docs?:'
            - '(?i)^docs\([^:]+\):'
            - '(?i)^docs\[[^:]+\]:'
            - '^tests?:'
            - '(?i)^dev:'
            - '(?i)^chore:'
            - '(?i)^style:'
            - '(?i)^refactor:'
            - '^build\(deps\): bump .* in /docs \(#\d+\)'
            - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
            - Merge pull request
            - Merge branch
release:
    skip_upload: false
    github:
        owner: fiffeek
        name: hyprdynamicmonitors

aurs:
    - description: Dynamic monitor configuration for Hyprland.
      skip_upload: false
      homepage: https://github.com/fiffeek/hyprdynamicmonitors
      provides:
          - hyprdynamicmonitors-bin
      maintainers:
          - Filip Mikina <filipmikina at gmail dot com>
      license: MIT
      private_key: '{{ .Env.AUR_KEY }}'
      git_url: ssh://aur@aur.archlinux.org/hyprdynamicmonitors-bin.git
      optdepends:
          - hyprland
          - upower
      commit_author:
          name: Filip Mikina
          email: filipmikina@gmail.con
      package: |-
          local x86_64=x86_64 i686=i386 aarch64=arm64
          cd "hyprdynamicmonitors-${pkgver}-linux-${!CARCH}"

          # bin
          install -Dm755 "./hyprdynamicmonitors" "${pkgdir}/usr/bin/hyprdynamicmonitors"

          # license
          install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/hyprdynamicmonitors/LICENSE"
