---
name: Deploy Docusaurus Docs

on:
    push:
        branches:
            - main
        paths:
            - docs/**

permissions:
    contents: write

jobs:
    deploy-docs:
        name: Build and Deploy Docs
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  lfs: true

            - name: Fetch and checkout LFS objects
              run: |
                  git lfs fetch --all
                  git lfs checkout

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24.6.0
                  cache: npm
                  cache-dependency-path: ./docs/package-lock.json

            - name: Install dependencies
              working-directory: ./docs
              run: npm ci

            - name: Build documentation
              working-directory: ./docs
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/build
                  user_name: github-actions[bot]
                  user_email: 41898282+github-actions[bot]@users.noreply.github.com
