---
name: Release a tag
on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  lfs: true

            - uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Fetch and checkout LFS objects
              run: |
                  git lfs fetch --all
                  git lfs checkout

            - name: Create release
              uses: goreleaser/goreleaser-action@v6
              with:
                  version: 2.11.2
                  args: release --clean --timeout=10m
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  AUR_KEY: ${{ secrets.AUR_KEY }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24.6.0
                  cache: npm
                  cache-dependency-path: ./docs/package-lock.json

            - name: Install dependencies
              working-directory: ./docs
              run: npm ci

            - name: Build documentation
              working-directory: ./docs
              run: |
                  npm run docusaurus docs:version ${{github.ref_name}}
                  npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/build
                  user_name: github-actions[bot]
                  user_email: 41898282+github-actions[bot]@users.noreply.github.com

            - name: Create PR for docs changes
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'docs: update version for ${{ github.ref_name }}'
                  title: 'chore(docs): update docs for ${{ github.ref_name }}'
                  body: |
                      Automated docs update for ${{ github.ref_name }} by GitHub Actions
                  branch: u/ga/docs/${{ github.ref_name }}
                  base: main
                  labels: documentation
