---
name: Release a tag
on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  lfs: true

            - uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Fetch and checkout LFS objects
              run: |
                  git lfs fetch --all
                  git lfs checkout

            - name: Create release
              uses: goreleaser/goreleaser-action@v6
              with:
                  version: 2.11.2
                  args: release --clean --timeout=10m
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  AUR_KEY: ${{ secrets.AUR_KEY }}
